### PR TITLE
Provide alternative implementation for gen_sas_token()

### PR DESCRIPTION
**Pull request by nmatthews-witekio**
Tested with symmetric key (SAS token) based left2myowndevice

### CODE REVIEW

**Comment by nmatthews-witekio** [comment]
I also copied iotc_algorithms_alternative.c to iotc_algorithms.c to use that alternative implementation -- still can connect to a symmetric key based device.

**Comment by nmatthews-witekio** [comment]
This still needs reviewing @PatriciaFieldhouse.

**Review by pywtk — COMMENTED** [review]
This looks like it moves a set of functions out of iotc_algorithms.c to iotc_algorithms_alternative.c.

It does this to facilitate the generation of SAS Tokens without using OpenSSL which isn't convenient on embedded systems.

By embedded systems do we mean MCUs or both MCUs and embedded Linux?

**Comment by nik-markovic** [comment]
I agree here with @pywtk - this SDK is targeted towards (what I called "generic" OSes) Windows/(embedded)Linux/MacOS and requires OpenSSL and paho MQTT implementation that requires OpenSSL. Since this code is completely generic, that is why I feel that this code should be added to the iotc-c-lib so that embedded projects can make use of it. 

I think this all started with @nmatthews-witekio thinking that this SDK was just suppsed to be *absolutely* generic or a reference project of some sort, which is not the case.

However, I can deffinitely see the **amazing value** that this implementation provides, especially since it is done "by hand" and no references to thirdpary code or pulling from Stackoverflow and such. I am glad that Neil separated it from the main code as reference so I don't have to think about sacrifices and complexities that it would introduce. That is why approve of this change and I will make it my personel crusade to get it into the c-lib once we figure out the way forward, given the pending AWS-related changes. I will also add unit test and try to test the code thoroughly.

**Review by nik-markovic — APPROVED** [review]

**Pull request merged**
