### PR TITLE
Improve encapsulation

### PR DESCRIPTION
**Pull request by nmatthews-witekio**
Try to hide structures -- improved encapsulation and avoid passing pointers out of the SDK.

### CODE REVIEW

**Review by nik-markovic — APPROVED** [review]

**Review by nik-markovic — CHANGES_REQUESTED** [review]
I don't see the need to provide setters for config options. It is a common practice that improves clarity for configuration, that for example paho mqtt client uses. Maybe we can improve based on the style for an initializer that they use?

**Review by nik-markovic — CHANGES_REQUESTED** [review]
I don't see the need to provide setters for config options. It is a common practice that improves clarity for configuration, that for example paho mqtt client uses. Maybe we can improve based on the style for an initializer that they use? (https://github.com/avnet-iotconnect/iotc-generic-c-sdk/blob/main/iotc-generic-c-sdk/paho-c-impl/src/iotc_paho_client.c#L91)

**Comment by nmatthews-witekio** [comment]
Reworked this.

Maybe needs a #ifdef access around the file checks -- am hoping it's a reasonable API to expect? But I can't test on all platforms.

**Comment by nik-markovic** [comment]
> Reworked this.
> 
> Maybe needs a #ifdef access around the file checks -- am hoping it's a reasonable API to expect? But I can't test on all platforms.

Sorry, I'm not getting what this question is about... Is this about the access(file) check? Can we just close this PR and delete the branch and then you can make the changes that you want?

**Comment by nmatthews-witekio** [comment]
Moving modifications to a separate branch for clarity -- and rebasing.

**Comment by nmatthews-witekio** [comment]
See: https://github.com/avnet-iotconnect/iotc-generic-c-sdk/pull/12

**Pull request closed without merging**
